cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2015冠军赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016 10 亚太青少年高尔夫菁英赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016 11-12 南翔镇青少年篮球训练营" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016 7 Asia-pacific & America" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016 8 NBA LEGEND STAR CHINA TOUR" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016 9The Tour of China" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016亚太精英赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016北京高尔夫" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2016“和谐杯”亚美对抗赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017 篮球3X3" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017GOLF" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017NBA" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017旅游局" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017环中赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017艺术体操" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017两大球预算" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017年拳赛策划" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017环法中国赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017高尔夫规划.doc" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017城市业余联赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017上海市民武术节" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017智地体育媒体通气会" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017篮球传奇中国行文件0511" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017“和谐杯”亚美对抗赛" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017年珠海市赛事活动安排" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2017发包出去的招商体育项目" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/2018五粮液乒乓球" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/Expansion Into China Deck_FINAL_fox highlights.pdf" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/MEDIA OPERATION" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/Mountest Women Volleyball" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/New P" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/RUNDOWN MUSIC" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/Tennis" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/cheerleading" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/desktop" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/reference" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/沙排" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/游泳" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/电竞" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/足球" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/飞镖" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/简报&政策" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/孙杨&菲尔普斯" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/体育+娱乐休闲业" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/标书+嘉定旅游局+商标注册+户外广告+房屋合同" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/星冰智" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/翔立方" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/中考体育" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/体育商业" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/关于报备" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/商标注册" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/园区广告" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/官摄报价" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/工作相关" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/智能体育" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/商业赛事.doc" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/企业运动会" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/体育电影节" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/关于高尔夫" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/新建文件夹" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/申办赛事请示" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/赛事招商方案" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/回款情况一览表.xlsx" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/休闲健身项目规划" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/禹唐体育合作协议.docx" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/还未收讫赞助商名录.docx" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/高尔夫夏令营课程参考.png" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/体育版块业务规划（篮球）" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/羽毛球——叶钊颖策划案（筹）" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
cp -r "/Volumes/TOSHIBA EXT/体育项目管理/世界企业高尔夫挑战赛中国系列赛 - 招商通案.pdf" "/Volumes/TOSHIBA EXT 1/xiaoying/体育项目管理/"
